CREATE TABLE good (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name VARCHAR NOT NULL,
                      description TEXT,
                      price NUMERIC(10, 2) NOT NULL
);