CREATE TABLE outbox_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR NOT NULL,
    payload TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    status VARCHAR NOT NULL DEFAULT 'NEW'
);

CREATE INDEX idx_outbox_new ON outbox_message (created_at)
WHERE status = 'NEW';